server:
  port: 8080

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /api/test/all*
      rate-limits:
        - bandwidths:
              # limit akses sebanyak 1 kali
            - capacity: 5
              # dalam 5 detik
              time: 1
              unit: minutes
    - cache-name: buckets
      url: /api/test/user*
      rate-limits:
        - bandwidths:
            - capacity: 6
              time: 1
              unit: minutes
    - cache-name: buckets
      url: /api/test/mod*
      rate-limits:
        - bandwidths:
            - capacity: 7
              time: 1
              unit: minutes
    - cache-name: buckets
      url: /api/test/admin*
      rate-limits:
        - bandwidths:
            - capacity: 8
              time: 1
              unit: minutes
    - cache-name: buckets
      url: /api/test/root*
      rate-limits:
        - bandwidths:
            - capacity: 9
              time: 1
              unit: minutes

spring:
  cache:
    jcache:
      config: ehcache.xml